server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: case-service
          uri: http://case-service:8081
          predicates:
            - Path=/cases/**

        - id: people-service
          uri: http://people-service:8082
          predicates:
            - Path=/people/**

        - id: evidence-service
          uri: http://evidence-service:8083
          predicates:
            - Path=/evidences/**

        - id: task-service
          uri: http://task-service:8084
          predicates:
            - Path=/tasks/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info